### ISSUE TITLE
Store user files in /home/yunohost.app directory

### ISSUE THREAD

**Issue by banquise** [YunoHost-Apps/lufi_ynh#51]
Yunohost apps generally store user files in the yunohost.app/"appname" directory
By default lufi store them in /var/www/lufi/files directory (Cf. /var/www/lufi/lufi.conf -> upload_dir)
Seems a good idea to isolate user files on /home partition to avoid they overload the /var partition
Would be more consistent with yunohost practices too.

**Comment by tiotrom** [comment]
Please do that. We host Lufi and our backups are enormous because of that. Luckily we fixed it manually and it is not that difficult:

Edit the file /var/www/lufi/lufi.conf and remove the # in front of "upload_dir". Now setup the path as  `upload_dir           => '/home/yunohost.app/lufi',` and make sure to create that folder + give the user "lufi" access to it. That's all. It works now as it should. Can you please implement this?

Cheers!
